"""
This Django app has been highly influenced by django tagulous
"""

from __future__ import unicode_literals

from django.utils import six


# Prefix for all models auto-generated by Tagulous
MODEL_PREFIX = 'Tag'

# Constants to improve code legibility
SPACE = ' '
HASH = '#'
DOUBLE_HASH = HASH + HASH

# Default model TagField options
OPTION_DEFAULTS = {
    'supertag_max_count': 3,
    'tag_max_count':        10,
    'sort_tag_by_alphabet': False,
    'tag_supertag_coexits': False,
    'tag_model': ['Tag.models.models', 'TagModel'],
    'to_user': ['Tag.models.models', 'GlobalTagRelation'],
    'to_global': ['Tag.models.models', 'UserTagRelation']
}
