# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GlobalTagRelation',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('filter_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.FilterTagModel')),
                ('post', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='Post.GeneralPost')),
            ],
        ),
        migrations.CreateModel(
            name='SuperTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserTagRelation',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('filter_tag', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.FilterTagModel')),
                ('post', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='Post.GeneralPost')),
                ('super_tag', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.SuperTagModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supertagmodel',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='globaltagrelation',
            name='super_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.SuperTagModel'),
        ),
        migrations.AlterUniqueTogether(
            name='filtertagmodel',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='usertagrelation',
            unique_together=set([('filter_tag', 'super_tag', 'post')]),
        ),
        migrations.AlterUniqueTogether(
            name='globaltagrelation',
            unique_together=set([('filter_tag', 'super_tag', 'post')]),
        ),
    ]
