# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('admin', models.BooleanField(default=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Normal User'), (2, 'Staff with no delete Authority'), (3, 'Staff with Authority up to Post delete'), (4, 'Staff with Authority up to User delete'), (5, 'Admin')], default=1)),
                ('active', models.BooleanField(default=False)),
                ('screen_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
