# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal User'), (2, 'Staff with no delete Authority'), (3, 'Staff with Authority up to Post delete'), (4, 'Staff with Authority up to User delete'), (5, 'Admin'), (6, 'Group User')], default=1),
        ),
    ]
