# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20181124_0856'),
        ('Account', '0002_user_phone_number'),
    ]

    operations = [
    ]
