# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_merge_20181222_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal User'), (2, 'Staff with no delete Authority'), (3, 'Staff with Authority up to Post delete'), (4, 'Staff with Authority up to User delete'), (5, 'Admin')], default=1),
        ),
    ]
