# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 12:22
from __future__ import unicode_literals

import Tag.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('did_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(blank=True, max_length=500000, null=True)),
                ('tags_json', Tag.models.fields.TagJSONFIELD(default=dict, init_options=[{'FILTERTAGMODEL': {'case_sensitive': False, 'classification': '#', 'force_lowercase': True, 'max_count': 10, 'path_name': ('Tag.models.models.FilterTagModel',), 'process_multiple_tags': False, 'sort_tag_by_alphabet': False, 'tag_rel': ('Tag.models.models.PostUserTagRelation', 'Tag.models.models.PostGlobalTagRelation')}}], more_than_one_model=True, tag_models=['FILTERTAGMODEL'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
