# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 01:10
from __future__ import unicode_literals

import Tag.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('did_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500000, null=True)),
                ('tags_json', Tag.models.fields.TagJSONFIELD(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
