# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-25 19:04
from __future__ import unicode_literals

import Tag.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='content',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='tags_json',
            field=Tag.models.fields.TagJSONFIELD(blank=True, default=dict),
        ),
    ]
