# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20181122_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpost',
            name='did_date',
        ),
        migrations.RemoveField(
            model_name='generalpost',
            name='last_edit_date',
        ),
        migrations.RemoveField(
            model_name='generalpost',
            name='pub_date',
        ),
    ]
