# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20181122_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpost',
            name='activity_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalpost',
            name='brief',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='did_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalpost',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='subTag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='generalpost',
            name='superTag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
