# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20181122_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='did_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
