# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20181122_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
