# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-22 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20181122_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpost',
            old_name='activity_date',
            new_name='activityDate',
        ),
        migrations.RenameField(
            model_name='generalpost',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='generalpost',
            old_name='brief',
            new_name='portfolioBrief',
        ),
        migrations.RenameField(
            model_name='generalpost',
            old_name='content',
            new_name='portfolioContent',
        ),
        migrations.RenameField(
            model_name='generalpost',
            old_name='title',
            new_name='portfolioTitle',
        ),
        migrations.RenameField(
            model_name='generalpost',
            old_name='last_edit_date',
            new_name='updated_at',
        ),
    ]
